### ISSUE TITLE
inquiring required versions 

### ISSUE THREAD

**Issue by shumailaahmed** [Cyberes/vitalsource2pdf#12]
I was looking to contribute to the project but couldn't get it running due to a dependencies mismatch, Can you share the Python version and dependencies versions that you are using?

**Comment by Cyberes** [comment]
https://stackoverflow.com/a/43070301
https://github.com/Cyberes/vitalsource2pdf#install

**Comment by Cyberes** [comment]
Actually, let me know if there's an issue with `pagelabels-py`: https://github.com/Cyberes/vitalsource2pdf/blob/master/requirements.txt#L8C5-L8C49
I don't think so, but it's possible.

**Comment by shumailaahmed** [comment]
Please share the Python version if possible, I guess you are working with Python 3.6?

**Comment by Cyberes** [comment]
Python 3.6 is EOL. Choose one from here: https://devguide.python.org/versions/
