### ISSUE TITLE
Program opens textbook, doesnt do anything from there

### ISSUE THREAD

**Issue by jacksonb2021** [Cyberes/vitalsource2pdf#4]
When i use the script, the program opens the textbook after logging in but never does anything with it. the page does not change from the cover, and nothing gets downloaded in the output folder

**Comment by jacksonb2021** [comment]
the page that is automatically opened is
https://bookshelf.vitalsource.com/reader/books/{isbn}/epubcfi/6/22[%3Bvnd.vst.idref%3Dt{author}{isbn}c00_02]!/4

I can go to 
 https://bookshelf.vitalsource.com/reader/books/{isbn}/pageid/{page_id}

but it will automatically redirect to the first URL.

sad day for me :(

**Comment by Cyberes** [comment]
Yup. I think I pissed off Vitalsource because they implemented some anti-scraping protections. Also, the CSS selectors are out of date so it won't work. Sorry, I don't have the time to fix this but check the forks: https://github.com/Cyberes/vitalsource2pdf/forks
