### ISSUE TITLE
Unable to open bookshelf books anymore after trying to run the script

### ISSUE THREAD

**Issue by Jonathankj12** [Cyberes/vitalsource2pdf#7]
I ran the script and completed the captcha when it appeared, but after a while I was automatically logged out.  

Now even when I try to access the books manually I am immediately logged out and sent to a page that won't let me log back in even for books I hadn't tried running the script on. 

Hopefully this is just a temporary timeout on my account.

**Comment by Cyberes** [comment]
Whine to customer support, act confused, and include a screenshot. They'll remove the block.
