### ISSUE TITLE
Is this code supported for PDF files only?

### ISSUE THREAD

**Issue by room-homage** [Cyberes/vitalsource2pdf#8]
I tried to run the code for a book in pbk format. Instead of ISBN I see VBID. 
The code did not output anything.
The book's URL matches with `https://bookshelf.vitalsource.com/reader/books/{isbn}/pageid/{page_id}`
instead of {isbn} it's VBID.

Would the software function in this case?

**Comment by Cyberes** [comment]
I don't think the scraper works right now because Vitalsource updated their platform.
